version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: phrase-service-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1234
      POSTGRES_DB: phrase-service-db
    ports:
      - "5432:5432"
    restart: always
